### ISSUE TITLE
Default onboarding flow results in wrong currency sent to community account

### ISSUE THREAD

**Issue by paulgoleary** [citizenwallet/app#118]
This came from BIllyR originally. 

Scenario:
1) individual downloaded CitizenWallet app and made an account but did not set up any wallets. 
2) I scanned their personal QR code to transfer 5 SFLUV
3) they were instantly set up with a Regen wallet
4) transaction / funds (0x9956e2cc6542b8546f3148563e21d9ceeeafa6e416798d1441bd33756cfa4abe) vanished from my account my account but did not populate into the a Regen and no SFLuv wallet  was automatically set up to receive. 
5) individual set up an SF wallet and a new transaction was completed successfully. (0x501a88ad35d547093e9ec8ac1a0c9cb737bc941a86645ad8645d5d6ba674a203)

My (PaulO) analysis:
What CW is calling the transaction ID is the TX hash that can be looked up easily on Polygonscan:

https://polygonscan.com/tx/0x9956e2cc6542b8546f3148563e21d9ceeeafa6e416798d1441bd33756cfa4abe

https://polygonscan.com/tx/0x501a88ad35d547093e9ec8ac1a0c9cb737bc941a86645ad8645d5d6ba674a203

Both are successful transfers of SFLuv but to two different addresses: 0x4814b574f77618d45C785416858011581020f481 and then 0xf1A86e86846A9210b2E7Bfe3Aab9BADA2505D68F.

So that's consistent with my understanding that CW sets up different accounts for each community. So bad UX but the funds are likely recoverable.

**Comment by kevtechi** [comment]
With the new deep linking page and account switcher, this is fixed.
