### ISSUE TITLE
Translate the existing app, english by default (and as a fallback), FR and NL as options

### ISSUE THREAD

**Issue by kev-techi** [citizenwallet/app#119]
Do it the standard way provided by Flutter. This needs to be set up.
https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#adding-your-own-localized-messages

- Use the user's device language to pick from EN, FR or NL automatically
- If their language is not one of the three configured languages, fall back to EN
- Provide a way to switch languages from the settings page

Cupertino Picker for the language picker: https://api.flutter.dev/flutter/cupertino/CupertinoPicker-class.html

**Comment by shanuka** [comment]
pr created
