### ISSUE TITLE
Show top up button when not enough fund on the send screen 

### ISSUE THREAD

**Issue by xdamman** [citizenwallet/app#155]
When we scan a QR code to send someone's money, it opens the send modal but if we don't have enough funds, we are stuck.
If there is the top up plugin for that community, it should show the button right there.

Instead of [ MAX ], it should show [ TOP UP ] when balance is zero or when "insufficient fund" error message is shown.

![7CD997AA-7400-455C-9C37-2B7CDF2C22F0_1_105_c](https://github.com/user-attachments/assets/24a66704-19c8-452e-9b79-811629c58a4f)

![92357301-DB39-433D-B755-43ACF38CFB15_4_5005_c](https://github.com/user-attachments/assets/8f52eff1-d4b7-4080-bd8e-aabb7179cb5d)

**Comment by kevtechi** [comment]
Noticed one thing:
- send button is disabled if 0. I guess we can remove that condition now if `action: topup` is set
