### ISSUE TITLE
Improve UX when scanning an address

### ISSUE THREAD

**Issue by xdamman** [citizenwallet/app#205]
When I scan a QR code that contains the `sendto` information (see #174), it should take me directly to the `enter amount screen`, not to the selection of the account.

- [ ] That `send screen` should populate the profile attached to the username or 0x address provided (it shows "anonymous" atm).
- [ ] The amount should be prefilled if defined in the QR code (it is not at the moment).

When scanning a QR code that specifies the 0x address:
![E7DE7635-71DD-4E73-A9D9-1B0F2C5E1CC3_1_102_o](https://github.com/user-attachments/assets/a38d938e-da84-41f2-8150-3d8df48058b2)

When scanning a QR code that specifies the username:
![D8586FAA-22FC-408F-B71E-57A9405E9BF9_1_102_o](https://github.com/user-attachments/assets/4ec480ce-57e4-4309-9787-bca944f315a8)

It should instead directly go to that screen:
![0C37B18A-F6D8-4DFE-9354-D634278BE885_1_102_o](https://github.com/user-attachments/assets/83268c44-4fc8-4137-82df-80df8d4ef1c8)

Here is a QR code you can use to test:
![qr-code (57)](https://github.com/user-attachments/assets/65ec0b1b-1144-4753-9c27-44edea8df02c)

https://live.citizenwallet.xyz/wallet.pay.brussels/fridge/pay?sendto=fridge@wallet.commonshub.brussels?description=Drinks&amount=3.00

And another one that leaves the amount undefined:
![qr-code (58)](https://github.com/user-attachments/assets/cd11e411-2f57-4ba6-aebb-118288353ea6)

https://live.citizenwallet.xyz/wallet.pay.brussels/fridge/pay?sendto=fridge@wallet.commonshub.brussels?description=Drinks

**Comment by SajeeTechi** [comment]
comment to self: this happens using the main scanner

**Comment by SajeeTechi** [comment]
Your message is mostly clear, but here’s a more concise version to make it even easier to follow:

@xdamman The URL you posted:

https://live.citizenwallet.xyz/wallet.pay.brussels/fridge/pay?sendto=fridge@wallet.commonshub.brussels?description=Drinks&amount=3.00

doesn’t follow the standard format. Normally, a single ? denotes the start of query parameters, and each parameter should be separated by an &.

Due to this, the app’s URL parser is unable to extract the amount value correctly. I’ll modify the parser to expect a format like this:

?sendto=fridge@wallet.commonshub.brussels &description=Drinks &amount=3.00

This way, it will correctly parse sendto, description, and amount.

**Comment by xdamman** [comment]
> doesn’t follow the standard format. Normally, a single ? denotes the start of query parameters, and each parameter should be separated by an &.

You are absolutely right, sorry it was a typo!

**Comment by SajeeTechi** [comment]
@xdamman i have a question about this

Does the `fridge` username actually belong to the `wallet.pay.brussels` community?

How the URL is created implies the `fridge` username belongs to the `wallet.commonshub.brussels` community. But within `wallet.commonshub.brussels` the `fridge` username does not exist.

**Comment by kevtechi** [comment]
Yes, usernames are scoped to communities.

**Comment by SajeeTechi** [comment]
The preference of the account address to

> Yes, usernames are scoped to communities.

I edited the QR code above to match

**Comment by xdamman** [comment]
Just tested the latest version 1.0.66 (214).
It works but it automatically takes the first account instead of giving me the choice if I have more than one.

**Comment by xdamman** [comment]
(it should only give me the choice to pick the account in the case when it has to switch community)
