### ISSUE TITLE
Add the name of the community in the title of the page for better bookmarking

### ISSUE THREAD

**Issue by xdamman** [citizenwallet/app#42]
Would be nice to show "OAK Wallet"  instead of "Citizen Wallet"

![IMG_3643](https://github.com/citizenwallet/app/assets/74358/7b386e84-19f5-43b4-b60e-da9a5672fae2)

**Comment by kev-techi** [comment]
14cec9be407216a4fc40c485d998ad99cd3fddb0 done

"add to Homescreen" functionality uses the PWA manifest.json which is compiled as a single file. We would need to generate a different one and serve it for that specific community to get it to work there

**Comment by kev-techi** [comment]
Also updated the title on the page itself to use the one from the community.

![IMG_7037](https://github.com/citizenwallet/app/assets/122159642/b60b9fb5-8e28-4c03-83fe-ea5d976c9b8a)
