### ISSUE TITLE
Update loading screen

### ISSUE THREAD

**Issue by xdamman** [citizenwallet/app#43]
see [figma.citizenwallet.xyz](https://www.figma.com/file/qwtJ5S8VDWMVvxRqgCvLrE/branding?type=design&node-id=0-1&mode=design&t=Dny0aIFv5ARmZK77-0)

I'd also suggest we make the gray lighter (from #E8E8E8 to #F1F1F1)

<img width="676" alt="Screenshot 2023-08-31 at 1 00 36 PM" src="https://github.com/citizenwallet/app/assets/74358/e7610bc9-5382-4da0-8a62-0aa9830c160c">

**Comment by kev-techi** [comment]
https://github.com/citizenwallet/app/pull/45
