### ISSUE TITLE
Transaction notifications

### ISSUE THREAD

**Issue by JonasBoury** [citizenwallet/app#62]
Would be great to receive notifications of incoming transactions

**Comment by xdamman** [comment]
As an MVP, in app notification would already be a great improvement. 
It's annoying when I show a QR code to receive money that I have to close it to see if the money has been received.

Also, sound notification is important. So that a vendor can just hear the confirmation.

**Comment by kev-techi** [comment]
Ended up doing both:

- in-app notifications when receiving
- push notifications
