### ISSUE TITLE
Any transaction that is sent appears twice until it is confirmed

### ISSUE THREAD

**Issue by xdamman** [citizenwallet/app#89]
![image](https://github.com/citizenwallet/app/assets/74358/b65fdae8-c2f1-4c7c-8ae1-e1530d4f8ac8)
![image](https://github.com/citizenwallet/app/assets/74358/60c1e402-9f41-4f7b-b2db-1260fd5fba21)

**Comment by kev-techi** [comment]
Fixed with the last few builds.
